version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        env_file:
          - ./.env
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        depends_on:
          - server
        networks:
          - common
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
          - ./.env
        depends_on:
          - pg-14
        networks:
          - common

    pg-14:
      env_file:
        - ./.env
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - ./db/db-init:/docker-entrypoint-initdb.d
        - ./db/db-data:/var/lib/postgresql/data
        - ./db/db-backups:/backup
      networks:
        - common

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - common


networks:
  common:
    driver: bridge