version: "3.9"

services:
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      restart: always
      command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/ssl/:/etc/nginx/ssl/
        - ./nginx/well-known:/etc/nginx/.well-known
        - ./nginx/.cache:/var/cache/nginx
      depends_on:
        - server
      networks:
        - common
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: 9000
              POSCGRES_PORT: 5432
              POSTRES_HOST: pg-14
        restart: always
        ports:
            - "9000:9000"
        env_file:
          - ./.env
        depends_on:
          - pg-14
        networks:
          - common

    pg-14:
      env_file:
        - ./.env
      environment:
        POSTGRES_PASSWORD: 11223344
        POSTGRES_USER: postgres
        POSTGRES_DB: memorybase
      image: postgres:14
      ports:
        - "5432:5432"
      volumes:
        - ./db/db-init:/docker-entrypoint-initdb.d
        - ./db/db-data:/var/lib/postgresql/data
        - ./db/db-backups:/backup
      networks:
        - common

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - common


networks:
  common:
    driver: bridge
