version: "3.9"

services:
    nginx:
      container_name: mg-nginx
      image: mg-nginx
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      ports:
        - "80:80"
        - "443:443"
      restart: always
      command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
      depends_on:
        - server
      networks:
        - common
    server:
        container_name: mg-server
        image: mg-server
        env_file:
          - ./.env
        build:
            context: .
            args:
              server_port: $SERVER_PORT
              postgres_port: $POSTGRES_PORT
              postgres_host: $POSTGRES_HOST
              postgres_user: $POSTGRES_USER
              postgres_password: $POSTGRES_PASSWORD
        restart: always
        ports:
            - "9000:9000"
        depends_on:
          - pg-14
        networks:
          - common

    pg-14:
      env_file:
        - ./.env
      image: postgres:14
      ports:
        - "5432:5432"
      volumes:
        - ./db/db-init:/docker-entrypoint-initdb.d
        - ./db/db-data:/var/lib/postgresql/data
        - ./db/db-backups:/backup
      networks:
        - common

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - common

networks:
  common:
    driver: bridge
