name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .env
        run: cp .env.sample .env
      - name: Build and push nginx image
        run: |
          docker-compose build nginx
          docker tag mg-nginx ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/mg-nginx:${{ github.sha }}
          docker push ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/mg-nginx:${{ github.sha }}

      - name: Build and push server image
        run: |
          docker-compose build server
          docker tag mg-server ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/mg-server:${{ github.sha }}
          docker push ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/mg-server:${{ github.sha }}
