name: Deploy to remote server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create certs
        run: |
          chmod 777 nginx/.ssl
          echo "$NGINX_CHAIN" > ./nginx/.ssl/certificate_full_chain.pem
          echo "$NGINX_KEY" > ./nginx/.ssl/private_key.pem
        env:
          NGINX_CHAIN: ${{ secrets.CERT_FULL_CHAIN }}
          NGINX_KEY: ${{ secrets.CERT_PRIVATE_KEY }}
      - name: Remove old files from server
        run: |
          scp -r ./clean.sh mg-admin@51.250.21.100:./
          ssh mg-admin@51.250.21.100 "pushd /home/mg-admin && sudo sh clean.sh && exit"
      - name: Copy files to server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          --exclude .github \
          --exclude  db \
          --exclude *.md \
          ./ mg-admin@51.250.21.100:~/memory-game
      - name: Restart the application
        run: |
          ssh mg-admin@51.250.21.100 "pushd /home/mg-admin/memory-game && sudo sh deploy.sh && exit"
