name: Deploy to remote server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACDPT2kWl4zuzBhaY7luPpwsxPVAqrboHUnJSCS99bdA8gAAALDbGed62xnn\negAAAAtzc2gtZWQyNTUxOQAAACDPT2kWl4zuzBhaY7luPpwsxPVAqrboHUnJSCS99bdA8g\nAAAEDrqqJF1vvmWqiEKeXz+HLjIUAoLBl4nnkphOp/LaMZY89PaRaXjO7MGFpjuW4+nCzE\n9UCqtugdSclIJL31t0DyAAAAKWFsZWtzZWpwZXRyZW5rb0BNYWNCb29rLVByby1BbGVrc2\nVqLmxvY2FsAQIDBA==\n-----END OPENSSH PRIVATE KEY-----\n" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          echo "158.160.74.247 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEsSTBWju73XuM2wiHqjJz55AF4h$" >> ~/.ssh/known_hosts
          echo "158.160.74.247 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCEUkW90iSswVmzXxkVSJqgCB3$" >> ~/.ssh/known_hosts
          echo "158.160.74.247 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAy$" >> ~/.ssh/known_hosts
        #env:
        #  SSH_PRIVATE_KEY: ${{ secrets.STARSHIP_PRIVATE_KEY }}
         # SSH_KNOWN_HOSTS: ${{ secrets.STARSHIP_KNOWN_HOSTS }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.sample .env
      - name: Remove old files from server
        run: |
          ssh mg-admin@158.160.74.247 "pushd /home/mg && sudo docker-compose down && sudo find . -maxdepth 1 ! -path "./db/db-data" -delete \; && exit"
      - name: Copy files to server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \

          --exclude .github \
          --exclude .env.sample \
          --exclude .eslintignore \
          --exclude .eslintrc.js \
          --exclude jest.config.js \
          --exclude *.md \
          ./ mg-admin@158.160.74.247:/home/mg
      - name: Restart the application
        run: |
          ssh mg-admin@158.160.74.247 "pushd /home/stovba/starship && sudo docker-compose down && sudo docker-compose build && sudo docker-compose up -d && find . -mindepth 1 ! -path "./db/db-data/*" ! -name "docker-compose.yml" -delete && ls -a"
