name: Deploy to remote server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDBS2fXAn\nAaRQJkNhagtSCuAAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDBD4d628U5\nPcYFFTmjskfzyYxpBHKMTJZn4Cq9+fatqJPm00bkDhuNTajNK7hc3XEFfNZSo58Ti7usk4\nCyjum/V7LbfMEfArbjolr/OtYNHNFZurEzk1OQEFWcOy2PO51wXEtaE6SD0vW+YMQh0gpo\nBeYz4tBtlBxBXoj6Zo1ytwE67llcRiiZyq6pUvXc7zpCG/iTrpNFz1cDeR6HCcc5dMYGd3\n4f+0SSWYQnblCHqWj7LtKvlPIqKbARpwOWAgakcngHouD/bINU8ay4aVhdb0LR+wMnXeuZ\nA2R82dtV37Ze5Hffxa3sc+FTQCdAYPaUEdhvMjtGqVxfjHwfNydN4sOAeyeGhk3giA+QpA\nKOt+bW3KYOOBdDNqQSK5cDHEvgFcN6myPZK9wo6lNumIcnTkNRfQ5hbECbl5FGCFtrsTza\nBi655Jffs6DkF/5gi4BTM8JI3+6h9kbI0EdoDDej7jQL8jIIMT8WGcgrqNxKhONP6ax6V7\nGK762/Nwl5V/sPvT6EBTsmTdy7vvczNAWHDmS19/ms5ZIOLLqOAdCz9ONMyK3Tx1GCyMag\nn/UZDeW40SSu0Hcv/gSKpC97svgPLbX5FKXyG4du+Qe6DSCMMgXIUf0xjcBbwT343sn1W7\nhFxbuD4d++JdEoS40XgCxBDedrimsPKB0nSZ9xGIJHjwAAB1Bon3SmoNwPmFNiqMzBxNqo\nbLJWbOW0IVqlOFSaklzgVewoKZxO0Mk/athtFF9gpXL0Qvj2o8BTM4iQdrp1vonuG1HU72\nBxFfvuNUWWdgq+9/vPh/STy8MaG++kAVg+El14rwlbAndduF2OPq+ENhkIZJRMqcXhTmQi\nAOqxS1lwUHCn61cH+WiBExQRvWIGwea0MNmzcxwHpR9KDWx788SR/9jpBZQQPYkcmOIUTu\npu/41oV8B4TE8cZw7mzQ1LKTejy/FRA9i0LLgyBXMAYu/irxr3AY1op3apvly0FwP+fDop\nl3zfoxpB6QFwwFvnOOxQSBmDohbna8PTeHT3EGIbd51viZfkkD43WHSLbsNkPJUdCxw7it\ng6RAsQ8RKz8eam+ai+kyOBBe3LFtcJdKhLJ3134Oavj3ev5pMahs9SI3oiF/VEyGdTU8W+\n7IHu9xWDGtaRYyoFHQ67uPDStLI7r5NQsnAXt48DOnT45GtObfgG5SKnHcrOTUJ6aI7fWF\nEpFtoHLx53xyEVxHTiMDH5RLl4EzgF1AF/kyyrsFZYQm0l1kXWq/YYqI/EaDWumacjGiLG\ndxGUg002SgpiCYrZYbyxh7heLE8Ja5ot+TRYO7cokl7HmI9+kt0RvsX3ExadL8IgQP4Hw2\nK0yikBWBRVoUHzUYqbsrLlSTlVbgARqH2G3sk9aRjkuxWZhw6uNVpJ2ngIgpvvFpny9Opa\nB+J7OgI1Js8kOettocOEtGM+qf9PgL8q10qWYteB991Grb7cLqAepgN0AHksG54hr8u/Gp\nFosjhowOuZUlvAPXo4LWSv2D+lMthOLMZNixbjIKtXy7dlFsq+SGstjpKzILceoTshiGsH\n1e4ggvdX1KYKndDmO3sTDNHkVODzuc1qZb3/CC7HmU67jxMrkTku6O4YXrkfhsHtE19FCR\nuueawZaUHKTAW3W5z4Snv4Y/dkm5blj86EyxhcumB0ezw6MoouQcc1JYwMfgjUxNiddvPd\nUaIPkCpjCWn9lpeZGaW/hoRyt2+9j9NnTnnn2fHhXMBFbJ2FFYMJF+yVAFwNl7sVLRW54a\ndKN9SyFMAHgAFCJxjS0nT1y7uMl/ZWRoA1KDuNgbUVFGnHijoRDY2V4KJ2/wpOYvb6wK7v\nQvZCBbmLawJ4wzHcK7XnYJ3nL/6lKHUgwZ3qVvkOcBXzdCV6z73zTRT7URzAhh830RNXmq\n9EM8gwfQYkiPsrcmNGLoiIwZ9hPn5fdbz/2FNQay+kvlaUwB5S7GBFJk9T9kWt4QX7xy69\nTTxMSZCtpTbO3ettoxtv2VITg9HInFSdeFRtCS0u6K2LIN8JEvDJABwo7BNX6zJ1W7KwZY\n+i25AnzCFldhxeNS0RSpgDl9eARXxHy2bdgvLfuh7GWiCMGt8AOfQt35rj3kwqN26hV4eg\nA8kor4EkmR0Fcqa8W9kZ3U6qng1PNEuarA9+oZn4iOkc6I1DxQf0TaWhqg67ExlkY7LfHE\nJPF7LQA+2cRSRXzcQeymS3UCgoV8zrz61y8rVCbxjAMQIofi8JH0NpAtH3xfVQWqbx3HX8\nJOo9V5iWDmlHQICwxeeTEqAdzzFI/D0eZiG77pw95okEqquJuS7H410OLOTF7O+gaLNkG3\nNoS0h46AdimZBiCBMNBCEAzKprKExtmTZgguanpOYetqow452fluLCJ0QDzSdbqq1mhPfS\nv6PisDEHUplLy8DPSY3Neh2AW2+8DjqoOIzH85a15lu7vxjPUJug2EeYNWdiuyx1MoZDLY\nL3idPljwRFoj1SyLMnNunJbVyzvJJ2HX+mlVb+n8I2zIzBDz7mgCwMP8YPENJhHMnzbs7G\nRNsIINqk6sfnOQXtXIDvKtpo+u8f6MMMMTq7y4vRC90Y6dfavuxskhy+tu/AtnWJ5nzB06\nU4SIKW+zt4/uhPHx/jiC6/BHF25dZsMcoLD1u5tJmuKGWr1eJ5flvZvJXnOWdxQcKYVdKp\nKWDiHJEM7f0vl/JmGnaG9MWCf6XdGsjLK3YPka32sAC0vJXg4uiXzrDSzpWFO1Rih+uGGT\ncY5yPTVAbaqnYmx3nupVVEyQXr2QOiUaPDE1xXTK/iKBvOkJYyOP+/zcmZaLRuj0YNxrCW\nArG5ZYnFGdI55TwbAU/b01vDXUdid7U1xeB2GZxqHX+L9KpyI0VXcKwTOrErHljZH6XAI9\nYmJEZalQQnjULNTdrXx7xu8CM7fDwP4FOqH+C5WTbZM8QUvq95cEgmB7THzbJ4MmkzhUEk\nrr46yDNdLu4IeIESiXEiBoIGFuhKyk8TFf5ToLiEvgEDUynxdYF0aVpkAOOJOFkH7wLOkY\nmwY5VhXiEast/VKenZLIAn4zeP71ZGhTjSwJUZ+BrHhUOJl0SXgLXQVPToAW8S/gCzVSZN\nE+OecFIgcAxCKBdOw2JVlIBONoaO2O7Dn+SaJ1NGK4RJ46OEyUJu52EBHwirIYto46vOYh\n9egRJz8ETQ4sKO6UhL2QhgYmM=\n-----END OPENSSH PRIVATE KEY-----\n" > ~/.ssh/id_rsa          
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "158.160.74.247 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEsSTBWju73XuM2wiHqjJz55AF4h$" >> ~/.ssh/known_hosts
          echo "158.160.74.247 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCEUkW90iSswVmzXxkVSJqgCB3$" >> ~/.ssh/known_hosts
          echo "158.160.74.247 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAy$" >> ~/.ssh/known_hosts
        #env:
        #  SSH_PRIVATE_KEY: ${{ secrets.STARSHIP_PRIVATE_KEY }}
         # SSH_KNOWN_HOSTS: ${{ secrets.STARSHIP_KNOWN_HOSTS }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.sample .env
      - name: Remove old files from server
        run: |
          ssh mg-admin@158.160.74.247 "pushd /home/mg && sudo docker-compose down && sudo find . -maxdepth 1 ! -path "./db/db-data" -delete \; && exit"
      - name: Copy files to server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \

          --exclude .github \
          --exclude .env.sample \
          --exclude .eslintignore \
          --exclude .eslintrc.js \
          --exclude jest.config.js \
          --exclude *.md \
          ./ mg-admin@158.160.74.247:/home/mg
      - name: Restart the application
        run: |
          ssh mg-admin@158.160.74.247 "pushd /home/stovba/starship && sudo docker-compose down && sudo docker-compose build && sudo docker-compose up -d && find . -mindepth 1 ! -path "./db/db-data/*" ! -name "docker-compose.yml" -delete && ls -a"
